-- Phase 1: Add the teacher_id column to the student_subjects table.
-- We add it as nullable first to allow for a default value to be set in the next step.
ALTER TABLE student_subjects
ADD COLUMN teacher_id UUID REFERENCES teachers(id) ON DELETE SET NULL;

-- Phase 2: Populate the new teacher_id column for all existing rows.
-- This uses the main teacher ID found in other parts of the applications history.
-- Replace this UUID if you have a different default teacher.
UPDATE student_subjects
SET teacher_id = 'dcef54de-bc89-4388-a7a8-dba5d8327447'
WHERE teacher_id IS NULL;

-- Phase 3: Now that all rows are populated, alter the column to be NOT NULL.
ALTER TABLE student_subjects
ALTER COLUMN teacher_id SET NOT NULL;

-- Phase 4: Drop the old unique constraint and create the new, more precise one.
-- The constraint name 'student_subjects_student_id_subject_key' is the default name
-- generated by PostgreSQL. If your constraint has a different name, you will need to change it here.
ALTER TABLE student_subjects
DROP CONSTRAINT student_subjects_student_id_subject_key,
ADD CONSTRAINT student_subjects_student_id_subject_teacher_id_key UNIQUE (student_id, subject, teacher_id);
