from enum import Enum
from typing import List

# Enums not auto-generated and not from database but used throughout the app
class PaidStatus(str, Enum):
    PAID = "Paid"
    UNPAID = "Unpaid"



# This file is auto-generated by generate_pg_enums.py
# Do not edit this file manually.

class FixedActivityCategoryEnum(Enum):
    GYM = 'Gym'
    SLEEP = 'Sleep'
    WORK = 'Work'
    MEAL = 'Meal'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class GymTypeEnum(Enum):
    PUSH = 'PUSH'
    PULL = 'PULL'
    LEG = 'LEG'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class LogStatusEnum(Enum):
    ACTIVE = 'ACTIVE'
    VOID = 'VOID'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class MealTypeEnum(Enum):
    MEALPREP = 'MEALPREP'
    BREAKFAST = 'BREAKFAST'
    SNACK = 'SNACK'
    LUNCH = 'LUNCH'
    DINNER = 'DINNER'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class RunStatusEnum(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    MANUAL = 'MANUAL'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class SessionCategoryEnum(Enum):
    GYM = 'Gym'
    SLEEP = 'Sleep'
    WORK = 'Work'
    MEAL = 'Meal'
    TUITION = 'Tuition'
    PRAYER = 'Prayer'
    CALENDAREVENT = 'CalendarEvent'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class SleepTypeEnum(Enum):
    NIGHT = 'NIGHT'
    NAP = 'NAP'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class StudentStatusEnum(Enum):
    NONE = 'NONE'
    ALPHA = 'Alpha'
    OMEGA = 'Omega'
    SIGMA = 'Sigma'
    HIM = 'HIM'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class SubjectEnum(Enum):
    MATH = 'Math'
    PHYSICS = 'Physics'
    CHEMISTRY = 'Chemistry'
    BIOLOGY = 'Biology'
    IT = 'IT'
    GEOGRAPHY = 'Geography'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class TuitionLogCreateTypeEnum(Enum):
    SCHEDULED = 'SCHEDULED'
    CUSTOM = 'CUSTOM'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class UserRole(Enum):
    ADMIN = 'admin'
    PARENT = 'parent'
    STUDENT = 'student'
    TEACHER = 'teacher'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]


class WorkTypeEnum(Enum):
    MAIN_JOB = 'MAIN_JOB'
    FREELANCE = 'FREELANCE'
    MAIN_JOB_FREELANCE = 'MAIN_JOB_FREELANCE'
    TUITION = 'TUITION'

    @classmethod
    def get_values(cls) -> List[str]:
        """Returns all string values of the enum."""
        return [e.value for e in cls]



